name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdl11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3
      - name: build
        run: ci/build-app.sh